// <auto-generated />
using System;
using ConcreteShipping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcreteShipping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309022420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ConcreteShipping.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "東京都江東区有明1-1-1",
                            ContactPerson = "山田太郎",
                            IsActive = true,
                            Name = "山田建設株式会社",
                            Phone = "03-1234-5678",
                            UnitPrice = 12000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "東京都墨田区押上2-2-2",
                            ContactPerson = "鈴木一郎",
                            IsActive = true,
                            Name = "鈴木工務店",
                            Phone = "03-2345-6789",
                            UnitPrice = 11500m
                        },
                        new
                        {
                            Id = 3,
                            Address = "神奈川県横浜市中区3-3-3",
                            ContactPerson = "佐藤次郎",
                            IsActive = true,
                            Name = "佐藤土木建設",
                            Phone = "045-345-6789",
                            UnitPrice = 11000m
                        });
                });

            modelBuilder.Entity("ConcreteShipping.Models.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Factories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "東京都江東区新木場4-4-4",
                            Name = "東京生コン第一工場",
                            Phone = "03-4567-8901"
                        });
                });

            modelBuilder.Entity("ConcreteShipping.Models.MixDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aggregate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slump")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MixDesigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aggregate = "20mm",
                            Code = "21N-8-20",
                            IsActive = true,
                            Name = "普通コンクリート 21N",
                            Slump = 8,
                            Strength = 21,
                            UnitPrice = 12000m
                        },
                        new
                        {
                            Id = 2,
                            Aggregate = "20mm",
                            Code = "24N-12-20",
                            IsActive = true,
                            Name = "普通コンクリート 24N",
                            Slump = 12,
                            Strength = 24,
                            UnitPrice = 13000m
                        },
                        new
                        {
                            Id = 3,
                            Aggregate = "25mm",
                            Code = "18N-15-25",
                            IsActive = true,
                            Name = "軽量コンクリート 18N",
                            Slump = 15,
                            Strength = 18,
                            UnitPrice = 11000m
                        });
                });

            modelBuilder.Entity("ConcreteShipping.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MixDesignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MixDesignId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DeliveryAddress = "東京都江東区有明1-1-1",
                            DeliveryDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 1,
                            Notes = "1便目 朝イチ希望",
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 30m,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DeliveryAddress = "東京都墨田区押上2-2-2",
                            DeliveryDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 2,
                            Notes = "",
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "Phone",
                            Quantity = 20m,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            DeliveryAddress = "神奈川県横浜市中区3-3-3",
                            DeliveryDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 1,
                            Notes = "雨天延期可",
                            OrderDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 15m,
                            Status = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            DeliveryAddress = "東京都江東区有明1-1-1 2工区",
                            DeliveryDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 3,
                            Notes = "",
                            OrderDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 25m,
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 2,
                            DeliveryAddress = "東京都墨田区押上2-2-2",
                            DeliveryDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 1,
                            Notes = "午後指定",
                            OrderDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "Phone",
                            Quantity = 18m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 3,
                            DeliveryAddress = "神奈川県横浜市中区3-3-3",
                            DeliveryDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 2,
                            Notes = "",
                            OrderDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 40m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 1,
                            DeliveryAddress = "東京都江東区有明1-1-1 3工区",
                            DeliveryDate = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 1,
                            Notes = "",
                            OrderDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 12m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 2,
                            DeliveryAddress = "東京都墨田区押上2-2-2",
                            DeliveryDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 3,
                            Notes = "基礎工事用",
                            OrderDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "Phone",
                            Quantity = 22m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 3,
                            DeliveryAddress = "神奈川県横浜市中区3-3-3",
                            DeliveryDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 2,
                            Notes = "",
                            OrderDate = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 35m,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 1,
                            DeliveryAddress = "東京都江東区有明1-1-1 大型案件",
                            DeliveryDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MixDesignId = 1,
                            Notes = "大型案件 要確認",
                            OrderDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderType = "PreOrder",
                            Quantity = 50m,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ConcreteShipping.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "",
                            OrderId = 1,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Notes = "",
                            OrderId = 1,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Notes = "",
                            OrderId = 1,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Notes = "",
                            OrderId = 2,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Notes = "",
                            OrderId = 2,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Notes = "",
                            OrderId = 3,
                            Quantity = 8m,
                            ShippedAt = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 7,
                            Notes = "",
                            OrderId = 3,
                            Quantity = 7m,
                            ShippedAt = new DateTime(2026, 3, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Dispatched",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Notes = "",
                            OrderId = 4,
                            Quantity = 10m,
                            ShippedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Dispatched",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 9,
                            Notes = "",
                            OrderId = 4,
                            Quantity = 8m,
                            ShippedAt = new DateTime(2026, 3, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Dispatched",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Notes = "",
                            OrderId = 4,
                            Quantity = 7m,
                            ShippedAt = new DateTime(2026, 3, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Dispatched",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 11,
                            Notes = "完了確認",
                            OrderId = 2,
                            Quantity = 0m,
                            ShippedAt = new DateTime(2026, 3, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("ConcreteShipping.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10m,
                            DriverName = "田中運転手",
                            IsActive = true,
                            LicensePlate = "品川100 あ 1234"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8m,
                            DriverName = "中村運転手",
                            IsActive = true,
                            LicensePlate = "品川100 い 5678"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 7m,
                            DriverName = "小林運転手",
                            IsActive = true,
                            LicensePlate = "品川100 う 9012"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConcreteShipping.Models.Order", b =>
                {
                    b.HasOne("ConcreteShipping.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcreteShipping.Models.MixDesign", "MixDesign")
                        .WithMany("Orders")
                        .HasForeignKey("MixDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MixDesign");
                });

            modelBuilder.Entity("ConcreteShipping.Models.Shipment", b =>
                {
                    b.HasOne("ConcreteShipping.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcreteShipping.Models.Vehicle", "Vehicle")
                        .WithMany("Shipments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcreteShipping.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ConcreteShipping.Models.MixDesign", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ConcreteShipping.Models.Order", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ConcreteShipping.Models.Vehicle", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
